// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aolpzyknlmvtontxyoep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbHB6eWtubG12dG9udHh5b2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjM5NTMsImV4cCI6MjA1NTE5OTk1M30.KYi76BrF8iWEbw2SZDykQBcAX7K42niBC9hLyUsk4TE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);